import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";


const scientifica = localfont({
  src: [
    {
      path: "./fonts/scientifica.ttf",
      weight: "400",
      style: "normal"
    },
    {
      path: "./fonts/scientificaBold.ttf",
      weight: "800",
      style: "bold"
    },
    {
      path: "./fonts/scientificaItalic.ttf",
      weight: "400",
      style: "italic"
    },
  ]
})

export const metadata: Metadata = {
  title: "THS Computer Science",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${scientifica.className} antialiased`}
      >
        <h1 className="font-bold">Hello World!</h1>
        {children}
      </body>
    </html>
  );
}
